import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Load local fonts with variable font support
const geistSans = localFont({
  src: "/fonts/GeistVF.woff", // Ensure the correct path
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff", // Ensure the correct path
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define the metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased ${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
